import type { Metadata } from "next";
import "@/app/globals.css";



export const metadata: Metadata = {
  title: "Sube una foto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-linear-to-br from-pink-50 to-purple-100">
        {children}
    </main>
  );
}
