import type { Metadata } from "next";
import { Geist_Mono, Great_Vibes, Inter} from "next/font/google";
import "./globals.css";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const sans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',        // evita flash de texto sin estilo
  preload: true,
})

const script = Great_Vibes({     // fuente cursiva bonita para "15 años"
  subsets: ['latin'],
  variable: '--font-script',
  weight: '400',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${geistMono.variable} ${script.variable}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-y-hidden">
        
        {children}
        
      </body>
    </html>
  );
}
